### ISSUE TITLE
test(pipeline): Add unit tests to database.js (SMALL/MEDIUM)

### ISSUE THREAD

**Issue by keskinmbaha** [cse110-fa21-group29/cse110-fa21-group29#194]
### Completed When

- [ ] Unit tests are written for 'database.js'

**Comment by Solowyhn** [comment]
using e2e instead, will come back if the error is solved.

**Comment by jbutera94** [comment]
Closed because e2e testing is sufficient to cover the database functionality and there are errors preventing us from unit testing it.
