### ISSUE TITLE
style(home-page): improve home page styling

### ISSUE THREAD

**Issue by jbutera94** [cse110-fa21-group29/cse110-fa21-group29#299]
### Suggestions from Dec 5 meeting

- [x] Change title font to Sophia
- [x] Maybe add transparent black line across entire picture
- [x] For titles, options:
    - [ ] instead of rectangle, make the right end into a flag
    - [x] or round the corners like how the recipe cards are rounded
- [x] Move categories to left align with the first recipe card in the grid and make it similiar design to GitHub Issues
- [x] Remove About Us and shrink team logo and add to Footer
- [ ] Ensure that recipes in grid are not duplicated
- [x] Add padding to bottom between content and footer

**Comment by edbertdai** [comment]
Added more tasks
