### ISSUE TITLE
style(meal-planner): improve meal planner styling

### ISSUE THREAD

**Issue by jbutera94** [cse110-fa21-group29/cse110-fa21-group29#305]
### Suggestions from Dec 5 meeting

- [x] Copy Clipboard image and functionality ~~next to print button~~
- ~~Make print button bigger~~
- ~~Default print layout to landscape~~
- ~~Lines disappear between Wednesday and Thursday in print preview~~
- [x] Number and units be in same line when search pops up
- [x] lowercase "c" in calories and add units to nutrition
- [x] Have fixed sidebar width

Edit:
Removing print function because I believe making the printout look good would involve another page or layout.
\- Edbert

**Comment by keskinmbaha** [comment]
I think by giving the recipe cards and min and max-width the same value, the width of the recipe cards do not change in the drag and drop, but now the cards touch the right side of the bar:
![Screen Shot 2021-12-08 at 1 00 40 PM](https://user-images.githubusercontent.com/62824264/145284214-9f56da17-bfb0-4aa2-b143-ec8d1c5b1df6.png)

Similarly, when the screen starts getting smaller, I think it would be best to abbreviate the 'Breakfast', 'Lunch', 'Dinner', and 'Total Nutrition' words to B, L, D, and TN or something along those lines so they do not overflow:
![Screen Shot 2021-12-08 at 1 00 44 PM](https://user-images.githubusercontent.com/62824264/145284226-f6b7952e-3850-40d7-ac43-c00069a39d41.png)
