### ISSUE TITLE
fix(home-page): going back randomizes the cards

### ISSUE THREAD

**Issue by keskinmbaha** [cse110-fa21-group29/cse110-fa21-group29#325]
### Issue as of Dec. 6th:

Starting off on the home page and getting random cards is nice, but when I go to a recipe detail, then click back to go home, the page re-randomizes the cards and I have now lost a recipe I would have liked to see.

### Completed When:

Not sure if we have the time or should fix this, but it is frustrating to the user when they lose a recipe they would have like to see.

**Comment by jbutera94** [comment]
This unfortunately is not possible due to time constraints impacting the ability to develop an interface to local storage to remember the recipes loaded.
