### ISSUE TITLE
bug(contribute-recipe): can't submit recipe with a photo

### ISSUE THREAD

**Issue by phamavery** [cse110-fa21-group29/cse110-fa21-group29#333]
Hitting the submit button doesn't do anything when I have a picture uploaded. I'm on Firefox. I tried with both JPEG and PNG

Expected Behavior: Should be able to submit a recipe with an image

Actual Behavior: Submit button doesn't do anything

Steps to reproduce:
1. Fill out required forms in contribute recipe
2. Upload a picture
3. Press submit button

Console complains about Firebase
<img width="950" alt="110-bug" src="https://user-images.githubusercontent.com/47911954/145005969-4c989795-5a5d-46a4-91de-6171c522d4f8.png">

**Comment by edbertdai** [comment]
The new Firebase storage bucket was not set up. I got it set up so image upload works again.
