### ISSUE TITLE
bug(meal-planner): Styling on filled in recipe cards not what it should be

### ISSUE THREAD

**Issue by j1morale** [cse110-fa21-group29/cse110-fa21-group29#344]
After dragging in a recipe, the title of recipe and statistics overlap one behavior. 

Expected Behavior: 
Be able to see title and statistics clearly.

Actual Behavior:
Title and stats overlap each other. 

Is this bug visible in all circumstances or is this is only in certain scenarios?
I'm using a 13.3 inch Mac to look at the website. 

<img width="1216" alt="Screen Shot 2021-12-07 at 10 51 23 PM" src="https://user-images.githubusercontent.com/50219916/145162597-58e33bc4-b09f-48b6-b077-74c712bc27b0.png">

**Comment by edbertdai** [comment]
Closed by accident
